### ISSUE TITLE
Display setting in Windows 10 (Possibly font issue)

### ISSUE THREAD

**Issue by roundaboutluke** [adocilesloth/LogiLCD#5]
Hi, have used the app pretty much since you released it and it works great. After upgrading to Windows 10, the app doesn't display properly, the text seems larger and almost like it's using a font - it still works 100%, but cuts off a few bits because of the oversizing.

I had a similar issue with ACT, turns out they removed a font from Win8 to Win10 that an overlay I had used, so it would fall back on another font. I found it in my Windows.Old file and installed the font and it works perfectly again.

I'd do it for this, but i can't seem to find what font it uses. Please excuse me if this is an issue with OBS and not your plugin, but it seems very similar to what I was having with ACT so thought it was worth asking what the font it uses is called just in case.

**Comment by adocilesloth** [comment]
I don't know what the font is as it is never set in the plugin itself, it's all done by the Logitech software on Logitech's end (at least in my app). I also can't find a reference to a font in the SDK documents either.

Unfortunately, I don't have a Win 10 system set up to test on yet so I can't go hunting for the problem. I'm assuming it will be a problem with my plugin and not OBS.

Thanks for letting me know! Once I have a Win 10 system up, I'll try and fix it as soon as I can.

**Comment by adocilesloth** [comment]
I have Windows 10 up and running and tried just recompiling inside of Windows 10 but that didn't fix the issue (it's never that easy). Now I have somewhere to test, hopefully I can find a fix.

**Comment by roundaboutluke** [comment]
Awesome! That was incredibly fast. If there's anything I can do to help please let me know.
- Edit 

Forgot to mention originally, this is on a G13, I noticed you updated the plugin to say it doesn't display properly on the color g19 variant in Win10 so if that's what you have and you don't have a monochrome please let me know if you need me to help test anything on my G13 relating to this, I'm more than happy to help if you need me.

**Comment by adocilesloth** [comment]
Tracked down the problem.
Bad behaviour is due to the missing font:
**MS Mincho Regular**

I leave finding the font online as a task for the reader.
