### ISSUE TITLE
No licence ?

### ISSUE THREAD

**Issue by 50thomatoes50** [adocilesloth/LogiLCD#6]
You didn't define any licence for this repo?

I'm doing a fork, do you allow me to use MIT licence?

**Comment by adocilesloth** [comment]
OBS is under GPLv2. So I guess that that license is more appropriate. Looking at the code, I copied some GPLv2 stuff into it. I dunno to be honest, I'm no lawyer.
Basically, as far as I'm concerned, you can go ahead and modify this code if you want to. Especially as OBS Classic and this plugin for it are both depreciated.

**Comment by 50thomatoes50** [comment]
GPLv2 it is then.

Not a lawyer either :)
